//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {{ cookiecutter.assembly_name }}.Api.PerformanceTests
{
    using System;
    using System.Collections.Generic;
    using LearnerRecords.API.PerformanceTests.Models;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using Newtonsoft.Json;
    using SharedServices.PerformanceTests.Constants;
    using SharedServices.PerformanceTests.Helpers;

    public class {{ cookiecutter.assembly_name }}WebTest : WebTest
    {
        private JwtTokenGenerator tokenGenerator;

        public {{ cookiecutter.assembly_name }}()
        {
            // Constructor Code
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
  
        }
    }
}

